server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server-uri:
      defaultZome: http://${eureka.instance.hostname}:${server.port}/eureka

